#!/bin/bash

# first cd /mnt/c/users/anama/onedrive/documents/labwork/proj-62bddf5ef3194eded6f9293d/bids/derivatives/upload

#Check whether the file subjList.txt exists; if not, create it
if [ ! -f subjList.txt ]; then
	ls | grep ^sub- > subjList.txt
fi

#Loop over all subjects 
for subj in `cat subjList.txt`; do
cd ${subj}/ses-7/func
  # Loop through tasks for smoothing
  for task in sem plaus gram; do
    3dmerge -1blur_fwhm 6.0 -doall -prefix r${task}_blur.nii \
            ${subj}_ses-7_task-${task}_*_bold.nii.gz
  done
  
  # Loop through tasks for scaling
  for task in sem plaus gram; do
  3dTstat -prefix rm.mean_r${task}.nii r${task}_blur.nii
  3dcalc -a r${task}_blur.nii -b rm.mean_r${task}.nii \
         -c ${subj}_ses-7_task-${task}_*_bold.nii.gz                          \
         -expr 'c * min(200, a/b*100)*step(a)*step(b)'       \
         -prefix r${task}_scale.nii
  done
  rm rm*
done
